---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: powerdns
  labels:
    {{- include "powerdns.labels" . | nindent 4 }}
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
