---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ironic
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  defaultBackend:
    service:
      name: ironic
      port:
        name: api
  rules:
    - host: api.ironic.suse.baremetal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ironic
                port:
                  name: api
    - host: inspector.ironic.suse.baremetal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ironic
                port:
                  name: inspector
    - host: boot.ironic.suse.baremetal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ironic
                port:
                  name: httpd
    - host: cache.ironic.suse.baremetal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ironic
                port:
                  name: httpd
