apiVersion: v1
kind: ConfigMap 
metadata:
  name: {{ include "ironic.fullname" . }}-bmo
  labels:
    {{- include "ironic.labels" . | nindent 4 }}
data:
  {{- with .Values.baremetaloperator }}      
  CACHEURL: {{ .cacheUrl }}
  DEPLOY_KERNEL_URL: {{ .deployKernelUrl }}
  DEPLOY_RAMDISK_URL: {{ .deployRamdiskUrl }}
  DHCP_RANGE: {{ .dhcpRange }}
  DNSMASQ_BOOT_SERVER_ADDRESS: {{ .bootServerAddress }}
  DNSMASQ_DEFAULT_ROUTER: {{ .dnsmasqDefaultRouter }}
  DNSMASQ_DNS_SERVER_ADDRESS: {{ .dnsmasqDnsServerAddress }}
  HTTP_PORT: {{ .httpPort | quote }}
  IPA_BASEURI: {{ .ipaBaseUri }}
  IRONIC_API_BASE_URL: {{ .ironicApiUrl }}
  IRONIC_API_HOST: {{ .ironicApiHost }}
  IRONIC_API_HTTPD_SERVER_NAME: {{ .ironicApiHost }}
  IRONIC_BOOT_BASE_URL: {{ .ironicBootBaseUrl }}
  IRONIC_ENDPOINT: {{ .ironicEndpoint }}
  IRONIC_INSPECTOR_BASE_URL: {{ .ironicInspectorUrl }} 
  IRONIC_INSPECTOR_ENDPOINT: {{ .ironicInspectorEndpoint }}
  IRONIC_INSPECTOR_HOST: {{ .ironicInspectorHost }}
  IRONIC_INSPECTOR_HTTPD_SERVER_NAME: {{ .ironicInspectorHost }}
  IRONIC_RAMDISK_SSH_KEY: {{ .ironicRamdiskSshKey }}
  IRONIC_VMEDIA_HTTPD_SERVER_NAME: {{ .bootServerAddress }} 
  PROVISIONING_INTERFACE: {{ .provisioningInterface }} 
  PROVISIONING_IP: {{ .provisioningIp }}
  {{- end }}
  IRONIC_INSPECTOR_VLAN_INTERFACES: all
  IRONIC_ILO_USE_SWIFT: "false"
  IRONIC_ILO_USE_WEB_SERVER_FOR_IMAGES: "true"
  RESTART_CONTAINER_CERTIFICATE_UPDATED: "false"
  IRONIC_FAST_TRACK: "true"
  IRONIC_REVERSE_PROXY_SETUP: "false"
  IRONIC_USE_MARIADB: "true"
  LISTEN_ALL_INTERFACES: "true"
  IRONIC_KERNEL_PARAMS: console=ttyS0
  RESTART_CONTAINER_CERTIFICATE_UPDATED: "false"

