apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ironic.fullname" . }}-dns-provider-credentials
  labels:
    {{- include "ironic.labels" . | nindent 4 }}
type: Opaque    
data:
  cloudfare_api_token: {{ .Values.baremetaloperator.cloudflareApiToken | toString | b64enc }}     
