apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: baremetal-operator-proxy-rolebinding
  labels:
    {{- include "baremetal-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: baremetal-operator-proxy-role
subjects:
- kind: ServiceAccount
  name: {{ include "baremetal-operator.serviceAccountName" . }}
  namespace: baremetal-operator-system
