apiVersion: v1
data:
  CACHEURL: http://cache.ironic.suse.baremetal/images
  DEPLOY_KERNEL_URL: http://boot.ironic.suse.baremetal/images/ironic-python-agent.kernel
  DEPLOY_RAMDISK_URL: http://boot.ironic.suse.baremetal/images/ironic-python-agent.initramfs
  DHCP_RANGE: 192.168.24.182,192.168.24.200
  HTTP_PORT: "6180"
  IRONIC_ENDPOINT: http://api.ironic.suse.baremetal/v1/
  IRONIC_FAST_TRACK: "true"
  IRONIC_INSPECTOR_ENDPOINT: http://inspector.ironic.suse.baremetal/v1/
  PROVISIONING_INTERFACE: ens3
  PROVISIONING_IP: 192.168.24.181
  RESTART_CONTAINER_CERTIFICATE_UPDATED: "false"
kind: ConfigMap
metadata:
  name: {{ include "baremetal-operator.fullname" . }}-ironic
  namespace: {{ include "baremetal-operator.fullname" . }}-system
  labels:
    {{- include "baremetal-operator.labels" . | nindent 4 }}
