apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: baremetal-operator-leader-election-rolebinding
  namespace: baremetal-operator-system
  labels:
    {{- include "baremetal-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: baremetal-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "baremetal-operator.serviceAccountName" . }}
  namespace: baremetal-operator-system
